// This file is generated automatically. Don't edit it.
declare namespace nodemod {
  /** Ham (Hamsandwich) hook result values */
  const enum HAM_RESULT {
    UNSET = 0, // Default state
    IGNORED = 1, // Hook had no effect, continue normally
    HANDLED = 2, // Hook processed the call, but still call original
    OVERRIDE = 3, // Use hook's return value instead of original
    SUPERCEDE = 4, // Don't call original function at all
  }

  /** Ham function IDs for virtual function hooking */
  const enum HAM_FUNC {
    Spawn = 0,
    Precache = 1,
    Keyvalue = 2,
    ObjectCaps = 3,
    Activate = 4,
    SetObjectCollisionBox = 5,
    Classify = 6,
    DeathNotice = 7,
    TraceAttack = 8,
    TakeDamage = 9,
    TakeHealth = 10,
    Killed = 11,
    BloodColor = 12,
    TraceBleed = 13,
    IsTriggered = 14,
    MyMonsterPointer = 15,
    MySquadMonsterPointer = 16,
    GetToggleState = 17,
    AddPoints = 18,
    AddPointsToTeam = 19,
    AddPlayerItem = 20,
    RemovePlayerItem = 21,
    GiveAmmo = 22,
    GetDelay = 23,
    IsMoving = 24,
    OverrideReset = 25,
    DamageDecal = 26,
    SetToggleState = 27,
    StartSneaking = 28,
    StopSneaking = 29,
    OnControls = 30,
    IsSneaking = 31,
    IsAlive = 32,
    IsBSPModel = 33,
    ReflectGauss = 34,
    HasTarget = 35,
    IsInWorld = 36,
    IsPlayer = 37,
    IsNetClient = 38,
    TeamId = 39,
    GetNextTarget = 40,
    Think = 41,
    Touch = 42,
    Use = 43,
    Blocked = 44,
    Respawn = 45,
    UpdateOwner = 46,
    FBecomeProne = 47,
    Center = 48,
    EyePosition = 49,
    EarPosition = 50,
    BodyTarget = 51,
    Illumination = 52,
    FVisible = 53,
    FVecVisible = 54,
    Player_Jump = 55,
    Player_Duck = 56,
    Player_PreThink = 57,
    Player_PostThink = 58,
    Player_GetGunPosition = 59,
    Player_ShouldFadeOnDeath = 60,
    Player_ImpulseCommands = 61,
    Player_UpdateClientData = 62,
    Item_AddToPlayer = 63,
    Item_AddDuplicate = 64,
    Item_CanDeploy = 65,
    Item_Deploy = 66,
    Item_CanHolster = 67,
    Item_Holster = 68,
    Item_UpdateItemInfo = 69,
    Item_PreFrame = 70,
    Item_PostFrame = 71,
    Item_Drop = 72,
    Item_Kill = 73,
    Item_AttachToPlayer = 74,
    Item_PrimaryAmmoIndex = 75,
    Item_SecondaryAmmoIndex = 76,
    Item_UpdateClientData = 77,
    Item_GetWeaponPtr = 78,
    Item_ItemSlot = 79,
    Weapon_ExtractAmmo = 80,
    Weapon_ExtractClipAmmo = 81,
    Weapon_AddWeapon = 82,
    Weapon_PlayEmptySound = 83,
    Weapon_ResetEmptySound = 84,
    Weapon_SendWeaponAnim = 85,
    Weapon_IsUsable = 86,
    Weapon_PrimaryAttack = 87,
    Weapon_SecondaryAttack = 88,
    Weapon_Reload = 89,
    Weapon_WeaponIdle = 90,
    Weapon_RetireWeapon = 91,
    Weapon_ShouldWeaponIdle = 92,
    Weapon_UseDecrement = 93,
    TS_BreakableRespawn = 94,
    TS_CanUsedThroughWalls = 95,
    TS_RespawnWait = 96,
    CS_Restart = 97,
    CS_RoundRespawn = 98,
    CS_Item_CanDrop = 99,
    CS_Item_GetMaxSpeed = 100,
    DOD_RoundRespawn = 101,
    DOD_RoundRespawnEnt = 102,
    DOD_RoundStore = 103,
    DOD_AreaSetIndex = 104,
    DOD_AreaSendStatus = 105,
    DOD_GetState = 106,
    DOD_GetStateEnt = 107,
    DOD_Item_CanDrop = 108,
    TFC_EngineerUse = 109,
    TFC_Finished = 110,
    TFC_EmpExplode = 111,
    TFC_CalcEmpDmgRad = 112,
    TFC_TakeEmpBlast = 113,
    TFC_EmpRemove = 114,
    TFC_TakeConcussionBlast = 115,
    TFC_Concuss = 116,
    ESF_IsEnvModel = 117,
    ESF_TakeDamage2 = 118,
    NS_GetPointValue = 119,
    NS_AwardKill = 120,
    NS_ResetEntity = 121,
    NS_UpdateOnRemove = 122,
    TS_GiveSlowMul = 123,
    TS_GoSlow = 124,
    TS_InSlow = 125,
    TS_IsObjective = 126,
    TS_EnableObjective = 127,
    TS_OnFreeEntPrivateData = 128,
    TS_ShouldCollide = 129,
    ChangeYaw = 130,
    HasHumanGibs = 131,
    HasAlienGibs = 132,
    FadeMonster = 133,
    GibMonster = 134,
    BecomeDead = 135,
    IRelationship = 136,
    PainSound = 137,
    ReportAIState = 138,
    MonsterInitDead = 139,
    Look = 140,
    BestVisibleEnemy = 141,
    FInViewCone = 142,
    FVecInViewCone = 143,
    GetDeathActivity = 144,
    RunAI = 145,
    MonsterThink = 146,
    MonsterInit = 147,
    CheckLocalMove = 148,
    Move = 149,
    MoveExecute = 150,
    ShouldAdvanceRoute = 151,
    GetStoppedActivity = 152,
    Stop = 153,
    CheckRangeAttack1 = 154,
    CheckRangeAttack2 = 155,
    CheckMeleeAttack1 = 156,
    CheckMeleeAttack2 = 157,
    ScheduleChange = 158,
    CanPlaySequence = 159,
    CanPlaySentence2 = 160,
    PlaySentence = 161,
    PlayScriptedSentence = 162,
    SentenceStop = 163,
    GetIdealState = 164,
    SetActivity = 165,
    CheckEnemy = 166,
    FTriangulate = 167,
    SetYawSpeed = 168,
    BuildNearestRoute = 169,
    FindCover = 170,
    CoverRadius = 171,
    FCanCheckAttacks = 172,
    CheckAmmo = 173,
    IgnoreConditions = 174,
    FValidateHintType = 175,
    FCanActiveIdle = 176,
    ISoundMask = 177,
    HearingSensitivity = 178,
    BarnacleVictimBitten = 179,
    BarnacleVictimReleased = 180,
    PrescheduleThink = 181,
    DeathSound = 182,
    AlertSound = 183,
    IdleSound = 184,
    StopFollowing = 185,
    CS_Weapon_SendWeaponAnim = 186,
    CS_Player_ResetMaxSpeed = 187,
    CS_Player_IsBot = 188,
    CS_Player_GetAutoaimVector = 189,
    CS_Player_Blind = 190,
    CS_Player_OnTouchingWeapon = 191,
    DOD_SetScriptReset = 192,
    DOD_Item_SpawnDeploy = 193,
    DOD_Item_SetDmgTime = 194,
    DOD_Item_DropGren = 195,
    DOD_Weapon_IsUseable = 196,
    DOD_Weapon_Aim = 197,
    DOD_Weapon_flAim = 198,
    DOD_Weapon_RemoveStamina = 199,
    DOD_Weapon_ChangeFOV = 200,
    DOD_Weapon_ZoomOut = 201,
    DOD_Weapon_ZoomIn = 202,
    DOD_Weapon_GetFOV = 203,
    DOD_Weapon_IsWaterSniping = 204,
    DOD_Weapon_UpdateZoomSpeed = 205,
    DOD_Weapon_Special = 206,
    TFC_DB_GetItemName = 207,
    TFC_RadiusDamage = 208,
    TFC_RadiusDamage2 = 209,
    ESF_IsFighter = 210,
    ESF_IsBuddy = 211,
    ESF_EmitSound = 212,
    ESF_EmitNullSound = 213,
    ESF_IncreaseStrength = 214,
    ESF_IncreasePL = 215,
    ESF_SetPowerLevel = 216,
    ESF_SetMaxPowerLevel = 217,
    ESF_StopAniTrigger = 218,
    ESF_StopFly = 219,
    ESF_HideWeapon = 220,
    ESF_ClientRemoveWeapon = 221,
    ESF_SendClientsCustomModel = 222,
    ESF_CanTurbo = 223,
    ESF_CanPrimaryFire = 224,
    ESF_CanSecondaryFire = 225,
    ESF_CanStopFly = 226,
    ESF_CanBlock = 227,
    ESF_CanRaiseKi = 228,
    ESF_CanRaiseStamina = 229,
    ESF_CanTeleport = 230,
    ESF_CanStartFly = 231,
    ESF_CanStartPowerup = 232,
    ESF_CanJump = 233,
    ESF_CanWallJump = 234,
    ESF_IsSuperJump = 235,
    ESF_IsMoveBack = 236,
    ESF_CheckWallJump = 237,
    ESF_EnableWallJump = 238,
    ESF_DisableWallJump = 239,
    ESF_ResetWallJumpVars = 240,
    ESF_GetWallJumpAnim = 241,
    ESF_GetWallJumpAnim2 = 242,
    ESF_SetWallJumpAnimation = 243,
    ESF_SetFlyMoveType = 244,
    ESF_IsFlyMoveType = 245,
    ESF_IsWalkMoveType = 246,
    ESF_SetWalkMoveType = 247,
    ESF_DrawChargeBar = 248,
    ESF_StartBlock = 249,
    ESF_StopBlock = 250,
    ESF_StartFly = 251,
    ESF_GetMaxSpeed = 252,
    ESF_SetAnimation = 253,
    ESF_PlayAnimation = 254,
    ESF_GetMoveForward = 255,
    ESF_GetMoveRight = 256,
    ESF_GetMoveUp = 257,
    ESF_AddBlindFX = 258,
    ESF_RemoveBlindFX = 259,
    ESF_DisablePSBar = 260,
    ESF_AddBeamBoxCrosshair = 261,
    ESF_RemoveBeamBoxCrosshair = 262,
    ESF_DrawPSWinBonus = 263,
    ESF_DrawPSBar = 264,
    ESF_LockCrosshair = 265,
    ESF_UnLockCrosshair = 266,
    ESF_RotateCrosshair = 267,
    ESF_UnRotateCrosshair = 268,
    ESF_WaterMove = 269,
    ESF_CheckTimeBasedDamage = 270,
    ESF_DoesSecondaryAttack = 271,
    ESF_DoesPrimaryAttack = 272,
    ESF_RemoveSpecialModes = 273,
    ESF_StopTurbo = 274,
    ESF_TakeBean = 275,
    ESF_GetPowerLevel = 276,
    ESF_RemoveAllOtherWeapons = 277,
    ESF_StopSwoop = 278,
    ESF_SetDeathAnimation = 279,
    ESF_SetModel = 280,
    ESF_AddAttacks = 281,
    ESF_EmitClassSound = 282,
    ESF_CheckLightning = 283,
    ESF_FreezeControls = 284,
    ESF_UnFreezeControls = 285,
    ESF_UpdateKi = 286,
    ESF_UpdateHealth = 287,
    ESF_GetTeleportDir = 288,
    ESF_Weapon_HolsterWhenMeleed = 289,
    NS_SetBoneController = 290,
    NS_SaveDataForReset = 291,
    NS_GetHull = 292,
    NS_GetMaxWalkSpeed = 293,
    NS_SetTeamID = 294,
    NS_GetEffectivePlayerClass = 295,
    NS_GetAuthenticationMask = 296,
    NS_EffectivePlayerClassChanged = 297,
    NS_NeedsTeamUpdate = 298,
    NS_SendTeamUpdate = 299,
    NS_SendWeaponUpdate = 300,
    NS_InitPlayerFromSpawn = 301,
    NS_PackDeadPlayerItems = 302,
    NS_GetAnimationForActivity = 303,
    NS_StartObserver = 304,
    NS_StopObserver = 305,
    NS_GetAdrenalineFactor = 306,
    NS_GetNamedItem = 307,
    NS_Suicide = 308,
    NS_GetCanUseWeapon = 309,
    NS_Weapon_GetWeapPrimeTime = 310,
    NS_Weapon_PrimeWeapon = 311,
    NS_Weapon_GetIsWeaponPrimed = 312,
    NS_Weapon_GetIsWeaponPriming = 313,
    NS_Weapon_DefaultDeploy = 314,
    NS_Weapon_DefaultReload = 315,
    NS_Weapon_GetDeployTime = 316,
    SC_GetClassification = 317,
    SC_IsMonster = 318,
    SC_IsPhysX = 319,
    SC_IsPointEntity = 320,
    SC_IsMachine = 321,
    SC_CriticalRemove = 322,
    SC_UpdateOnRemove = 323,
    SC_FVisible = 324,
    SC_FVisibleFromPos = 325,
    SC_IsFacings = 326,
    SC_GetPointsForDamage = 327,
    SC_GetDamagePoints = 328,
    SC_OnCreate = 329,
    SC_OnDestroy = 330,
    SC_IsValidEntity = 331,
    SC_ShouldFadeOnDeath = 332,
    SC_SetupFriendly = 333,
    SC_ReviveThink = 334,
    SC_Revive = 335,
    SC_StartMonster = 336,
    SC_CheckRangeAttack1_Move = 337,
    SC_CheckRangeAttack2_Move = 338,
    SC_CheckMeleeAttack1_Move = 339,
    SC_CheckMeleeAttack2_Move = 340,
    SC_CheckTankUsage = 341,
    SC_SetGaitActivity = 342,
    SC_FTriangulate = 343,
    SC_FTriangulateExtension = 344,
    SC_FindCoverGrenade = 345,
    SC_FindCoverDistance = 346,
    SC_FindAttackPoint = 347,
    SC_FValidateCover = 348,
    SC_NoFriendlyFire1 = 349,
    SC_NoFriendlyFire2 = 350,
    SC_NoFriendlyFire3 = 351,
    SC_NoFriendlyFireToPos = 352,
    SC_FVisibleGunPos = 353,
    SC_FInBulletCone = 354,
    SC_CallGibMonster = 355,
    SC_CheckTimeBasedDamage = 356,
    SC_IsMoving = 357,
    SC_IsPlayerFollowing = 358,
    SC_StartPlayerFollowing = 359,
    SC_StopPlayerFollowing = 360,
    SC_UseSound = 361,
    SC_UnUseSound = 362,
    SC_RideMonster = 363,
    SC_CheckApplyGenericAttacks = 364,
    SC_CheckScared = 365,
    SC_CheckCreatureDanger = 366,
    SC_CheckFallDamage = 367,
    SC_CheckRevival = 368,
    SC_MedicCallSound = 369,
    SC_Player_MenuInputPerformed = 370,
    SC_Player_IsMenuInputDone = 371,
    SC_Player_SpecialSpawn = 372,
    SC_Player_IsValidInfoEntity = 373,
    SC_Player_LevelEnd = 374,
    SC_Player_VoteStarted = 375,
    SC_Player_CanStartNextVote = 376,
    SC_Player_Vote = 377,
    SC_Player_HasVoted = 378,
    SC_Player_ResetVote = 379,
    SC_Player_LastVoteInput = 380,
    SC_Player_InitVote = 381,
    SC_Player_TimeToStartNextVote = 382,
    SC_Player_ResetView = 383,
    SC_Player_GetLogFrequency = 384,
    SC_Player_LogPlayerStats = 385,
    SC_Player_DisableCollisionWithPlayer = 386,
    SC_Player_EnableCollisionWithPlayer = 387,
    SC_Player_CanTouchPlayer = 388,
    SC_Item_Materialize = 389,
    SC_Weapon_BulletAccuracy = 390,
    SC_Weapon_TertiaryAttack = 391,
    SC_Weapon_BurstSupplement = 392,
    SC_Weapon_GetP_Model = 393,
    SC_Weapon_GetW_Model = 394,
    SC_Weapon_GetV_Model = 395,
    SC_Weapon_PrecacheCustomModels = 396,
    SC_Weapon_IsMultiplayer = 397,
    SC_Weapon_FRunfuncs = 398,
    SC_Weapon_SetFOV = 399,
    SC_Weapon_FCanRun = 400,
    SC_Weapon_CustomDecrement = 401,
    SC_Weapon_SetV_Model = 402,
    SC_Weapon_SetP_Model = 403,
    SC_Weapon_ChangeWeaponSkin = 404,
    TFC_Killed = 405,
    TFC_IsTriggered = 406,
    TFC_Weapon_SendWeaponAnim = 407,
    TFC_Weapon_GetNextAttackDelay = 408,
    SC_TakeHealth = 409,
    SC_TakeArmor = 410,
    SC_GiveAmmo = 411,
    SC_CheckAttacker = 412,
    SC_Player_IsConnected = 413,
    DOD_Weapon_SendWeaponAnim = 414,
    CS_Item_IsWeapon = 415,
    OPF_MySquadTalkMonsterPointer = 416,
    OPF_WeaponTimeBase = 417,
    TS_Weapon_AlternateAttack = 418,
    Item_GetItemInfo = 419,
    SC_PreSpawn = 420,
    SC_PostSpawn = 421,
    SC_OnKeyValueUpdate = 422,
    SC_SetClassification = 423,
    SC_IsTriggered = 424,
    SC_MyCustomPointer = 425,
    SC_MyItemPointer = 426,
    SC_AddPoints = 427,
    SC_AddPointsToTeam = 428,
    SC_RemovePlayerItem = 429,
    SC_OnControls = 430,
    SC_IsSneaking = 431,
    SC_IsAlive = 432,
    SC_IsBSPModel = 433,
    SC_ReflectGauss = 434,
    SC_HasTarget = 435,
    SC_IsInWorld = 436,
    SC_IsPlayer = 437,
    SC_IsNetClient = 438,
    SC_IsBreakable = 439,
    SC_SUB_UseTargets = 440,
    SC_IsLockedByMaster = 441,
    SC_FBecomeProne = 442,
    SC_FVecVisible = 443,
    SC_SetPlayerAlly = 444,
    SC_OnSetOriginByMap = 445,
    SC_IsRevivable = 446,
    SC_BeginRevive = 447,
    SC_EndRevive = 448,
    SC_CanPlaySequence = 449,
    SC_CanPlaySentence2 = 450,
    SC_PlayScriptedSentence = 451,
    SC_Item_AddToPlayer = 452,
    SC_Item_AddDuplicate = 453,
    SC_Item_AddAmmoFromItem = 454,
    SC_Item_GetPickupSound = 455,
    SC_Item_CanCollect = 456,
    SC_Item_Collect = 457,
    SC_Item_GetItemInfo = 458,
    SC_Item_CanDeploy = 459,
    SC_Item_Deploy = 460,
    SC_Item_CanHolster = 461,
    SC_Item_InactiveItemPreFrame = 462,
    SC_Item_InactiveItemPostFrame = 463,
    SC_Item_DetachFromPlayer = 464,
    SC_Item_UpdateClientData = 465,
    SC_Item_GetRespawnTime = 466,
    SC_Item_CanHaveDuplicates = 467,
    SC_Weapon_ExtractAmmoFromItem = 468,
    SC_Weapon_AddWeapon = 469,
    SC_Weapon_GetAmmo1Drop = 470,
    SC_Weapon_GetAmmo2Drop = 471,
    SC_Weapon_PlayEmptySound = 472,
    SC_Weapon_IsUsable = 473,
    SC_Weapon_FinishReload = 474,
    SC_Weapon_ShouldReload = 475,
    SC_Weapon_ShouldWeaponIdle = 476,
    SC_Weapon_UseDecrement = 477,
    SC_Player_EnteredObserver = 478,
    SC_Player_LeftObserver = 479,
    SC_Player_IsObserver = 480,
  }

  // Ham callback type mappings - maps HAM_FUNC to callback signature
  // All callbacks receive 'this_' (the hooked entity) as the first parameter
  type HamCallbackFor<T extends HAM_FUNC> =
    T extends HAM_FUNC.Spawn ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Precache ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Keyvalue ? (this_: Entity, str: string) => HAM_RESULT | void :
    T extends HAM_FUNC.ObjectCaps ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Activate ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SetObjectCollisionBox ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Classify ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.DeathNotice ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.TraceAttack ? (this_: Entity, attacker: Entvars, damage: number, direction: number[], trace: TraceResult, damageBits: number) => HAM_RESULT | void :
    T extends HAM_FUNC.TakeDamage ? (this_: Entity, inflictor: Entvars, attacker: Entvars, damage: number, damageBits: number) => HAM_RESULT | number :
    T extends HAM_FUNC.TakeHealth ? (this_: Entity, value: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.Killed ? (this_: Entity, attacker: Entvars, gibType: number) => HAM_RESULT | void :
    T extends HAM_FUNC.BloodColor ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.TraceBleed ? (this_: Entity, damage: number, direction: number[], trace: TraceResult) => HAM_RESULT | void :
    T extends HAM_FUNC.IsTriggered ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.MyMonsterPointer ? (this_: Entity) => HAM_RESULT | Entity :
    T extends HAM_FUNC.MySquadMonsterPointer ? (this_: Entity) => HAM_RESULT | Entity :
    T extends HAM_FUNC.GetToggleState ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.AddPoints ? (this_: Entity, score: number, allowNegative: number) => HAM_RESULT | void :
    T extends HAM_FUNC.AddPointsToTeam ? (this_: Entity, score: number, allowNegative: number) => HAM_RESULT | void :
    T extends HAM_FUNC.AddPlayerItem ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.RemovePlayerItem ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.GiveAmmo ? (this_: Entity, amount: number, name: string, max: number) => HAM_RESULT | number :
    T extends HAM_FUNC.GetDelay ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.IsMoving ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.OverrideReset ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.DamageDecal ? (this_: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SetToggleState ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.StartSneaking ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.StopSneaking ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.OnControls ? (this_: Entity, other: Entvars) => HAM_RESULT | number :
    T extends HAM_FUNC.IsSneaking ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.IsAlive ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.IsBSPModel ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ReflectGauss ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.HasTarget ? (this_: Entity, str: string) => HAM_RESULT | number :
    T extends HAM_FUNC.IsInWorld ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.IsPlayer ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.IsNetClient ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.TeamId ? (this_: Entity) => HAM_RESULT | string :
    T extends HAM_FUNC.GetNextTarget ? (this_: Entity) => HAM_RESULT | Entity :
    T extends HAM_FUNC.Think ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Touch ? (this_: Entity, other: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Use ? (this_: Entity, activator: Entity, caller: Entity, useType: number, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.Blocked ? (this_: Entity, other: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Respawn ? (this_: Entity) => HAM_RESULT | Entity :
    T extends HAM_FUNC.UpdateOwner ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.FBecomeProne ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Center ? (this_: Entity) => HAM_RESULT | number[] :
    T extends HAM_FUNC.EyePosition ? (this_: Entity) => HAM_RESULT | number[] :
    T extends HAM_FUNC.EarPosition ? (this_: Entity) => HAM_RESULT | number[] :
    T extends HAM_FUNC.BodyTarget ? (this_: Entity, vec: number[]) => HAM_RESULT | number[] :
    T extends HAM_FUNC.Illumination ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.FVisible ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.FVecVisible ? (this_: Entity, vec: number[]) => HAM_RESULT | number :
    T extends HAM_FUNC.Player_Jump ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Player_Duck ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Player_PreThink ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Player_PostThink ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Player_GetGunPosition ? (this_: Entity) => HAM_RESULT | number[] :
    T extends HAM_FUNC.Player_ShouldFadeOnDeath ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Player_ImpulseCommands ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Player_UpdateClientData ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Item_AddToPlayer ? (this_: Entity, player: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Item_AddDuplicate ? (this_: Entity, original: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Item_CanDeploy ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Item_Deploy ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Item_CanHolster ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Item_Holster ? (this_: Entity, skipLocal: number) => HAM_RESULT | void :
    T extends HAM_FUNC.Item_UpdateItemInfo ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Item_PreFrame ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Item_PostFrame ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Item_Drop ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Item_Kill ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Item_AttachToPlayer ? (this_: Entity, other: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Item_PrimaryAmmoIndex ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Item_SecondaryAmmoIndex ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Item_UpdateClientData ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Item_GetWeaponPtr ? (this_: Entity) => HAM_RESULT | Entity :
    T extends HAM_FUNC.Item_ItemSlot ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Weapon_ExtractAmmo ? (this_: Entity, weapon: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Weapon_ExtractClipAmmo ? (this_: Entity, weapon: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Weapon_AddWeapon ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Weapon_PlayEmptySound ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Weapon_ResetEmptySound ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Weapon_SendWeaponAnim ? (this_: Entity, value1: number, value2: number, value3: number) => HAM_RESULT | void :
    T extends HAM_FUNC.Weapon_IsUsable ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Weapon_PrimaryAttack ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Weapon_SecondaryAttack ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Weapon_Reload ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Weapon_WeaponIdle ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Weapon_RetireWeapon ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Weapon_ShouldWeaponIdle ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Weapon_UseDecrement ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.TS_BreakableRespawn ? (this_: Entity, respawnTime: number) => HAM_RESULT | number :
    T extends HAM_FUNC.TS_CanUsedThroughWalls ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.TS_RespawnWait ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.CS_Restart ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.CS_RoundRespawn ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.CS_Item_CanDrop ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.CS_Item_GetMaxSpeed ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.DOD_RoundRespawn ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.DOD_RoundRespawnEnt ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.DOD_RoundStore ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.DOD_AreaSetIndex ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.DOD_AreaSendStatus ? (this_: Entity, other: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.DOD_GetState ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.DOD_GetStateEnt ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.DOD_Item_CanDrop ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.TFC_EngineerUse ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.TFC_Finished ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.TFC_EmpExplode ? (this_: Entity, other: Entvars, value1: number, value2: number) => HAM_RESULT | void :
    T extends HAM_FUNC.TFC_CalcEmpDmgRad ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | void :
    T extends HAM_FUNC.TFC_TakeEmpBlast ? (this_: Entity, other: Entvars) => HAM_RESULT | void :
    T extends HAM_FUNC.TFC_EmpRemove ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.TFC_TakeConcussionBlast ? (this_: Entity, other: Entvars, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.TFC_Concuss ? (this_: Entity, other: Entvars) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_IsEnvModel ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_TakeDamage2 ? (this_: Entity, other1: Entvars, other2: Entvars, value1: number, value2: number, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_GetPointValue ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_AwardKill ? (this_: Entity, other: Entvars) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_ResetEntity ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_UpdateOnRemove ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.TS_GiveSlowMul ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.TS_GoSlow ? (this_: Entity, duration: number, mode: number) => HAM_RESULT | void :
    T extends HAM_FUNC.TS_InSlow ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.TS_IsObjective ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.TS_EnableObjective ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.TS_OnFreeEntPrivateData ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.TS_ShouldCollide ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ChangeYaw ? (this_: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.HasHumanGibs ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.HasAlienGibs ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.FadeMonster ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.GibMonster ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.BecomeDead ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.IRelationship ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.PainSound ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ReportAIState ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.MonsterInitDead ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Look ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.BestVisibleEnemy ? (this_: Entity) => HAM_RESULT | Entity :
    T extends HAM_FUNC.FInViewCone ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.FVecInViewCone ? (this_: Entity, vec: number[]) => HAM_RESULT | number :
    T extends HAM_FUNC.GetDeathActivity ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.RunAI ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.MonsterThink ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.MonsterInit ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.CheckLocalMove ? (this_: Entity, vec1: number[], vec2: number[], other: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.Move ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.MoveExecute ? (this_: Entity, other: Entity, vec: number[], value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ShouldAdvanceRoute ? (this_: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.GetStoppedActivity ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.Stop ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.CheckRangeAttack1 ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.CheckRangeAttack2 ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.CheckMeleeAttack1 ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.CheckMeleeAttack2 ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.ScheduleChange ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.CanPlaySequence ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.CanPlaySentence2 ? (this_: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.PlaySentence ? (this_: Entity, str: string, value1: number, value2: number, value3: number) => HAM_RESULT | void :
    T extends HAM_FUNC.PlayScriptedSentence ? (this_: Entity, str: string, value1: number, value2: number, value3: number, value: number, other: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SentenceStop ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.GetIdealState ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SetActivity ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.CheckEnemy ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.FTriangulate ? (this_: Entity, vec1: number[], vec2: number[], value: number, other: Entity, vec3: number[]) => HAM_RESULT | number :
    T extends HAM_FUNC.SetYawSpeed ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.BuildNearestRoute ? (this_: Entity, vec1: number[], vec2: number[], value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.FindCover ? (this_: Entity, vec1: number[], vec2: number[], value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.CoverRadius ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.FCanCheckAttacks ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.CheckAmmo ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.IgnoreConditions ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.FValidateHintType ? (this_: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.FCanActiveIdle ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ISoundMask ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.HearingSensitivity ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.BarnacleVictimBitten ? (this_: Entity, other: Entvars) => HAM_RESULT | void :
    T extends HAM_FUNC.BarnacleVictimReleased ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.PrescheduleThink ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.DeathSound ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.AlertSound ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.IdleSound ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.StopFollowing ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.CS_Weapon_SendWeaponAnim ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | void :
    T extends HAM_FUNC.CS_Player_ResetMaxSpeed ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.CS_Player_IsBot ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.CS_Player_GetAutoaimVector ? (this_: Entity, value: number) => HAM_RESULT | number[] :
    T extends HAM_FUNC.CS_Player_Blind ? (this_: Entity, value1: number, value2: number, value3: number, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.CS_Player_OnTouchingWeapon ? (this_: Entity, other: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.DOD_SetScriptReset ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.DOD_Item_SpawnDeploy ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.DOD_Item_SetDmgTime ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.DOD_Item_DropGren ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.DOD_Weapon_IsUseable ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.DOD_Weapon_Aim ? (this_: Entity, value: number, other: Entity, value2: number) => HAM_RESULT | number[] :
    T extends HAM_FUNC.DOD_Weapon_flAim ? (this_: Entity, value: number, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.DOD_Weapon_RemoveStamina ? (this_: Entity, value: number, other: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.DOD_Weapon_ChangeFOV ? (this_: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.DOD_Weapon_ZoomOut ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.DOD_Weapon_ZoomIn ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.DOD_Weapon_GetFOV ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.DOD_Weapon_IsWaterSniping ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.DOD_Weapon_UpdateZoomSpeed ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.DOD_Weapon_Special ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.TFC_DB_GetItemName ? (this_: Entity) => HAM_RESULT | string :
    T extends HAM_FUNC.TFC_RadiusDamage ? (this_: Entity, other1: Entvars, other2: Entvars, value: number, value1: number, value2: number) => HAM_RESULT | void :
    T extends HAM_FUNC.TFC_RadiusDamage2 ? (this_: Entity, vec: number[], other1: Entvars, other2: Entvars, value: number, value1: number, value2: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_IsFighter ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_IsBuddy ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_EmitSound ? (this_: Entity, str: string, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_EmitNullSound ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_IncreaseStrength ? (this_: Entity, other: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_IncreasePL ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_SetPowerLevel ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_SetMaxPowerLevel ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_StopAniTrigger ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_StopFly ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_HideWeapon ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_ClientRemoveWeapon ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_SendClientsCustomModel ? (this_: Entity, str: string) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_CanTurbo ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_CanPrimaryFire ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_CanSecondaryFire ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_CanStopFly ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_CanBlock ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_CanRaiseKi ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_CanRaiseStamina ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_CanTeleport ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_CanStartFly ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_CanStartPowerup ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_CanJump ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_CanWallJump ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_IsSuperJump ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_IsMoveBack ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_CheckWallJump ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_EnableWallJump ? (this_: Entity, vec: number[]) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_DisableWallJump ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_ResetWallJumpVars ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_GetWallJumpAnim ? (this_: Entity, str1: string, vec: number[], str2: string) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_GetWallJumpAnim2 ? (this_: Entity, str1: string, str2: string) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_SetWallJumpAnimation ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_SetFlyMoveType ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_IsFlyMoveType ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_IsWalkMoveType ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_SetWalkMoveType ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_DrawChargeBar ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_StartBlock ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_StopBlock ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_StartFly ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_GetMaxSpeed ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_SetAnimation ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_PlayAnimation ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_GetMoveForward ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_GetMoveRight ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_GetMoveUp ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_AddBlindFX ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_RemoveBlindFX ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_DisablePSBar ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_AddBeamBoxCrosshair ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_RemoveBeamBoxCrosshair ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_DrawPSWinBonus ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_DrawPSBar ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_LockCrosshair ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_UnLockCrosshair ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_RotateCrosshair ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_UnRotateCrosshair ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_WaterMove ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_CheckTimeBasedDamage ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_DoesSecondaryAttack ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_DoesPrimaryAttack ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.ESF_RemoveSpecialModes ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_StopTurbo ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_TakeBean ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_GetPowerLevel ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_RemoveAllOtherWeapons ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_StopSwoop ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_SetDeathAnimation ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_SetModel ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_AddAttacks ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_EmitClassSound ? (this_: Entity, str1: string, str2: string, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_CheckLightning ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_FreezeControls ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_UnFreezeControls ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_UpdateKi ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_UpdateHealth ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.ESF_GetTeleportDir ? (this_: Entity) => HAM_RESULT | number[] :
    T extends HAM_FUNC.ESF_Weapon_HolsterWhenMeleed ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_SetBoneController ? (this_: Entity, value: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_SaveDataForReset ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_GetHull ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_GetMaxWalkSpeed ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_SetTeamID ? (this_: Entity, str: string) => HAM_RESULT | string :
    T extends HAM_FUNC.NS_GetEffectivePlayerClass ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_GetAuthenticationMask ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_EffectivePlayerClassChanged ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_NeedsTeamUpdate ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_SendTeamUpdate ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_SendWeaponUpdate ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_InitPlayerFromSpawn ? (this_: Entity, other: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_PackDeadPlayerItems ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_GetAnimationForActivity ? (this_: Entity, value1: number, str: string, value2: number) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_StartObserver ? (this_: Entity, vec1: number[], vec2: number[]) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_StopObserver ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_GetAdrenalineFactor ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_GetNamedItem ? (this_: Entity, str: string, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_Suicide ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_GetCanUseWeapon ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_Weapon_GetWeapPrimeTime ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_Weapon_PrimeWeapon ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.NS_Weapon_GetIsWeaponPrimed ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_Weapon_GetIsWeaponPriming ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_Weapon_DefaultDeploy ? (this_: Entity, str1: string, str2: string, value1: number, str3: string, value2: number, value3: number) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_Weapon_DefaultReload ? (this_: Entity, value1: number, value2: number, value: number, value3: number) => HAM_RESULT | number :
    T extends HAM_FUNC.NS_Weapon_GetDeployTime ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_GetClassification ? (this_: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_IsMonster ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_IsPhysX ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_IsPointEntity ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_IsMachine ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_CriticalRemove ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_UpdateOnRemove ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_FVisible ? (this_: Entity, other: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_FVisibleFromPos ? (this_: Entity, vec1: number[], vec2: number[]) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_IsFacings ? (this_: Entity, other: Entvars, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_GetPointsForDamage ? (this_: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_GetDamagePoints ? (this_: Entity, other1: Entvars, other2: Entvars, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_OnCreate ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_OnDestroy ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_IsValidEntity ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_ShouldFadeOnDeath ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_SetupFriendly ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_ReviveThink ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Revive ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_StartMonster ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_CheckRangeAttack1_Move ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_CheckRangeAttack2_Move ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_CheckMeleeAttack1_Move ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_CheckMeleeAttack2_Move ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_CheckTankUsage ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_SetGaitActivity ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_FTriangulate ? (this_: Entity, vec1: number[], vec2: number[], value: number, other: Entity, vec3: number[], vec4: number[], value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_FTriangulateExtension ? (this_: Entity, vec1: number[], vec2: number[], value: number, other: Entity, vec3: number[]) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_FindCoverGrenade ? (this_: Entity, vec1: number[], vec2: number[], value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_FindCoverDistance ? (this_: Entity, vec1: number[], vec2: number[], value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_FindAttackPoint ? (this_: Entity, vec1: number[], vec2: number[], value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_FValidateCover ? (this_: Entity, vec: number[]) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_NoFriendlyFire1 ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_NoFriendlyFire2 ? (this_: Entity, vec: number[]) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_NoFriendlyFire3 ? (this_: Entity, vec: number[], other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_NoFriendlyFireToPos ? (this_: Entity, vec: number[]) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_FVisibleGunPos ? (this_: Entity, other: Entity, vec: number[]) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_FInBulletCone ? (this_: Entity, other: Entity, vec: number[]) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_CallGibMonster ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_CheckTimeBasedDamage ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_IsMoving ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_IsPlayerFollowing ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_StartPlayerFollowing ? (this_: Entity, other: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_StopPlayerFollowing ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_UseSound ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_UnUseSound ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_RideMonster ? (this_: Entity, other: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_CheckApplyGenericAttacks ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_CheckScared ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_CheckCreatureDanger ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_CheckFallDamage ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_CheckRevival ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_MedicCallSound ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_MenuInputPerformed ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_IsMenuInputDone ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_SpecialSpawn ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_IsValidInfoEntity ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Player_LevelEnd ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_VoteStarted ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_CanStartNextVote ? (this_: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Player_Vote ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_HasVoted ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Player_ResetVote ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_LastVoteInput ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Player_InitVote ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_TimeToStartNextVote ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Player_ResetView ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_GetLogFrequency ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Player_LogPlayerStats ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Player_DisableCollisionWithPlayer ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_EnableCollisionWithPlayer ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_CanTouchPlayer ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Item_Materialize ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Weapon_BulletAccuracy ? (this_: Entity, vec1: number[], vec2: number[], vec3: number[], vec4: number[]) => HAM_RESULT | number[] :
    T extends HAM_FUNC.SC_Weapon_TertiaryAttack ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Weapon_BurstSupplement ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Weapon_GetP_Model ? (this_: Entity, str: string) => HAM_RESULT | string :
    T extends HAM_FUNC.SC_Weapon_GetW_Model ? (this_: Entity, str: string) => HAM_RESULT | string :
    T extends HAM_FUNC.SC_Weapon_GetV_Model ? (this_: Entity, str: string) => HAM_RESULT | string :
    T extends HAM_FUNC.SC_Weapon_PrecacheCustomModels ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Weapon_IsMultiplayer ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Weapon_FRunfuncs ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Weapon_SetFOV ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Weapon_FCanRun ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Weapon_CustomDecrement ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Weapon_SetV_Model ? (this_: Entity, str: string) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Weapon_SetP_Model ? (this_: Entity, str: string) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Weapon_ChangeWeaponSkin ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.TFC_Killed ? (this_: Entity, other1: Entvars, other2: Entvars, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.TFC_IsTriggered ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.TFC_Weapon_SendWeaponAnim ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | void :
    T extends HAM_FUNC.TFC_Weapon_GetNextAttackDelay ? (this_: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_TakeHealth ? (this_: Entity, value: number, value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_TakeArmor ? (this_: Entity, value: number, value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_GiveAmmo ? (this_: Entity, value1: number, str: string, value2: number, value3: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_CheckAttacker ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Player_IsConnected ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.DOD_Weapon_SendWeaponAnim ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | void :
    T extends HAM_FUNC.CS_Item_IsWeapon ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.OPF_MySquadTalkMonsterPointer ? (this_: Entity) => HAM_RESULT | Entity :
    T extends HAM_FUNC.OPF_WeaponTimeBase ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.TS_Weapon_AlternateAttack ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.Item_GetItemInfo ? (this_: Entity, itemInfo: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_PreSpawn ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_PostSpawn ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_OnKeyValueUpdate ? (this_: Entity, str: string) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_SetClassification ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_IsTriggered ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_MyCustomPointer ? (this_: Entity) => HAM_RESULT | Entity :
    T extends HAM_FUNC.SC_MyItemPointer ? (this_: Entity) => HAM_RESULT | Entity :
    T extends HAM_FUNC.SC_AddPoints ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_AddPointsToTeam ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_RemovePlayerItem ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_OnControls ? (this_: Entity, other: Entvars) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_IsSneaking ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_IsAlive ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_IsBSPModel ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_ReflectGauss ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_HasTarget ? (this_: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_IsInWorld ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_IsPlayer ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_IsNetClient ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_IsBreakable ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_SUB_UseTargets ? (this_: Entity, other: Entity, value: number, value2: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_IsLockedByMaster ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_FBecomeProne ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_FVecVisible ? (this_: Entity, vec: number[]) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_SetPlayerAlly ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_OnSetOriginByMap ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_IsRevivable ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_BeginRevive ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_EndRevive ? (this_: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_CanPlaySequence ? (this_: Entity, value1: number, value2: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_CanPlaySentence2 ? (this_: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_PlayScriptedSentence ? (this_: Entity, str: string, value1: number, value2: number, value3: number, value: number, other: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Item_AddToPlayer ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Item_AddDuplicate ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Item_AddAmmoFromItem ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Item_GetPickupSound ? (this_: Entity) => HAM_RESULT | string :
    T extends HAM_FUNC.SC_Item_CanCollect ? (this_: Entity, other: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Item_Collect ? (this_: Entity, other: Entity, value: number) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Item_GetItemInfo ? (this_: Entity, value: number) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Item_CanDeploy ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Item_Deploy ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Item_CanHolster ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Item_InactiveItemPreFrame ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Item_InactiveItemPostFrame ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Item_DetachFromPlayer ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Item_UpdateClientData ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Item_GetRespawnTime ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Item_CanHaveDuplicates ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Weapon_ExtractAmmoFromItem ? (this_: Entity, other: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Weapon_AddWeapon ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Weapon_GetAmmo1Drop ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Weapon_GetAmmo2Drop ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Weapon_PlayEmptySound ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Weapon_IsUsable ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Weapon_FinishReload ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Weapon_ShouldReload ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Weapon_ShouldWeaponIdle ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Weapon_UseDecrement ? (this_: Entity) => HAM_RESULT | number :
    T extends HAM_FUNC.SC_Player_EnteredObserver ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_LeftObserver ? (this_: Entity) => HAM_RESULT | void :
    T extends HAM_FUNC.SC_Player_IsObserver ? (this_: Entity) => HAM_RESULT | number :
    (this_: Entity, ...args: any[]) => HAM_RESULT | void;

  // Ham (Hamsandwich) virtual function hooking
  interface Ham {
    /** Register a ham hook on an entity class's virtual function with typed callback */
    register<F extends HAM_FUNC>(functionId: F, entityClass: string, callback: HamCallbackFor<F>, isPre: boolean): number;
    /** Unregister a ham hook by ID */
    unregister(hookId: number): void;
    /** Set the return value for the hooked function */
    setReturn(value: any): void;
    /** Get the current return value */
    getReturn(): any;
    /** Get the original return value */
    getOrigReturn(): any;
    /** Set result to SUPERCEDE (skip original function) */
    supercede(): void;
    /** Set result to OVERRIDE (use hook's return value) */
    override(): void;
    /** Set result to HANDLED (original still executes) */
    handled(): void;
    /** Set result to IGNORED (no effect) */
    ignored(): void;
    /** Ham function constants */
    readonly funcs: typeof HAM_FUNC;
    /** Ham result constants */
    readonly result: typeof HAM_RESULT;
  }
  const ham: Ham;
}